/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as RegistrosRouteImport } from './routes/registros'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsuariosEliminarRouteImport } from './routes/usuarios.eliminar'
import { Route as UsuariosCrearRouteImport } from './routes/usuarios.crear'
import { Route as UsuariosBuscarRouteImport } from './routes/usuarios.buscar'
import { Route as UsuariosActualizarRouteImport } from './routes/usuarios.actualizar'
import { Route as ReservasLugaresRouteImport } from './routes/reservas.lugares'
import { Route as ReservasArticulosRouteImport } from './routes/reservas.articulos'
import { Route as PerfilValoracionMedicaRouteImport } from './routes/perfil.valoracion-medica'
import { Route as PerfilDatosPersonalesRouteImport } from './routes/perfil.datos-personales'
import { Route as PerfilDatosFamiliaresRouteImport } from './routes/perfil.datos-familiares'
import { Route as PerfilDatosAcademicosRouteImport } from './routes/perfil.datos-academicos'
import { Route as DeportesListarRouteImport } from './routes/deportes.listar'
import { Route as DeportesEliminarRouteImport } from './routes/deportes.eliminar'
import { Route as DeportesCrearRouteImport } from './routes/deportes.crear'
import { Route as DeportesBuscarRouteImport } from './routes/deportes.buscar'
import { Route as DeportesActualizarRouteImport } from './routes/deportes.actualizar'
import { Route as CategoriasListarRouteImport } from './routes/categorias.listar'
import { Route as CategoriasEliminarRouteImport } from './routes/categorias.eliminar'
import { Route as CategoriasCrearRouteImport } from './routes/categorias.crear'
import { Route as CategoriasBuscarRouteImport } from './routes/categorias.buscar'
import { Route as CategoriasActualizarRouteImport } from './routes/categorias.actualizar'

const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrosRoute = RegistrosRouteImport.update({
  id: '/registros',
  path: '/registros',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosEliminarRoute = UsuariosEliminarRouteImport.update({
  id: '/usuarios/eliminar',
  path: '/usuarios/eliminar',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosCrearRoute = UsuariosCrearRouteImport.update({
  id: '/usuarios/crear',
  path: '/usuarios/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosBuscarRoute = UsuariosBuscarRouteImport.update({
  id: '/usuarios/buscar',
  path: '/usuarios/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosActualizarRoute = UsuariosActualizarRouteImport.update({
  id: '/usuarios/actualizar',
  path: '/usuarios/actualizar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasLugaresRoute = ReservasLugaresRouteImport.update({
  id: '/lugares',
  path: '/lugares',
  getParentRoute: () => ReservasRoute,
} as any)
const ReservasArticulosRoute = ReservasArticulosRouteImport.update({
  id: '/articulos',
  path: '/articulos',
  getParentRoute: () => ReservasRoute,
} as any)
const PerfilValoracionMedicaRoute = PerfilValoracionMedicaRouteImport.update({
  id: '/perfil/valoracion-medica',
  path: '/perfil/valoracion-medica',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilDatosPersonalesRoute = PerfilDatosPersonalesRouteImport.update({
  id: '/perfil/datos-personales',
  path: '/perfil/datos-personales',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilDatosFamiliaresRoute = PerfilDatosFamiliaresRouteImport.update({
  id: '/perfil/datos-familiares',
  path: '/perfil/datos-familiares',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilDatosAcademicosRoute = PerfilDatosAcademicosRouteImport.update({
  id: '/perfil/datos-academicos',
  path: '/perfil/datos-academicos',
  getParentRoute: () => rootRouteImport,
} as any)
const DeportesListarRoute = DeportesListarRouteImport.update({
  id: '/deportes/listar',
  path: '/deportes/listar',
  getParentRoute: () => rootRouteImport,
} as any)
const DeportesEliminarRoute = DeportesEliminarRouteImport.update({
  id: '/deportes/eliminar',
  path: '/deportes/eliminar',
  getParentRoute: () => rootRouteImport,
} as any)
const DeportesCrearRoute = DeportesCrearRouteImport.update({
  id: '/deportes/crear',
  path: '/deportes/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const DeportesBuscarRoute = DeportesBuscarRouteImport.update({
  id: '/deportes/buscar',
  path: '/deportes/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const DeportesActualizarRoute = DeportesActualizarRouteImport.update({
  id: '/deportes/actualizar',
  path: '/deportes/actualizar',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasListarRoute = CategoriasListarRouteImport.update({
  id: '/categorias/listar',
  path: '/categorias/listar',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasEliminarRoute = CategoriasEliminarRouteImport.update({
  id: '/categorias/eliminar',
  path: '/categorias/eliminar',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasCrearRoute = CategoriasCrearRouteImport.update({
  id: '/categorias/crear',
  path: '/categorias/crear',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasBuscarRoute = CategoriasBuscarRouteImport.update({
  id: '/categorias/buscar',
  path: '/categorias/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasActualizarRoute = CategoriasActualizarRouteImport.update({
  id: '/categorias/actualizar',
  path: '/categorias/actualizar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/horarios': typeof HorariosRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/registros': typeof RegistrosRoute
  '/reservas': typeof ReservasRouteWithChildren
  '/categorias/actualizar': typeof CategoriasActualizarRoute
  '/categorias/buscar': typeof CategoriasBuscarRoute
  '/categorias/crear': typeof CategoriasCrearRoute
  '/categorias/eliminar': typeof CategoriasEliminarRoute
  '/categorias/listar': typeof CategoriasListarRoute
  '/deportes/actualizar': typeof DeportesActualizarRoute
  '/deportes/buscar': typeof DeportesBuscarRoute
  '/deportes/crear': typeof DeportesCrearRoute
  '/deportes/eliminar': typeof DeportesEliminarRoute
  '/deportes/listar': typeof DeportesListarRoute
  '/perfil/datos-academicos': typeof PerfilDatosAcademicosRoute
  '/perfil/datos-familiares': typeof PerfilDatosFamiliaresRoute
  '/perfil/datos-personales': typeof PerfilDatosPersonalesRoute
  '/perfil/valoracion-medica': typeof PerfilValoracionMedicaRoute
  '/reservas/articulos': typeof ReservasArticulosRoute
  '/reservas/lugares': typeof ReservasLugaresRoute
  '/usuarios/actualizar': typeof UsuariosActualizarRoute
  '/usuarios/buscar': typeof UsuariosBuscarRoute
  '/usuarios/crear': typeof UsuariosCrearRoute
  '/usuarios/eliminar': typeof UsuariosEliminarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/horarios': typeof HorariosRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/registros': typeof RegistrosRoute
  '/reservas': typeof ReservasRouteWithChildren
  '/categorias/actualizar': typeof CategoriasActualizarRoute
  '/categorias/buscar': typeof CategoriasBuscarRoute
  '/categorias/crear': typeof CategoriasCrearRoute
  '/categorias/eliminar': typeof CategoriasEliminarRoute
  '/categorias/listar': typeof CategoriasListarRoute
  '/deportes/actualizar': typeof DeportesActualizarRoute
  '/deportes/buscar': typeof DeportesBuscarRoute
  '/deportes/crear': typeof DeportesCrearRoute
  '/deportes/eliminar': typeof DeportesEliminarRoute
  '/deportes/listar': typeof DeportesListarRoute
  '/perfil/datos-academicos': typeof PerfilDatosAcademicosRoute
  '/perfil/datos-familiares': typeof PerfilDatosFamiliaresRoute
  '/perfil/datos-personales': typeof PerfilDatosPersonalesRoute
  '/perfil/valoracion-medica': typeof PerfilValoracionMedicaRoute
  '/reservas/articulos': typeof ReservasArticulosRoute
  '/reservas/lugares': typeof ReservasLugaresRoute
  '/usuarios/actualizar': typeof UsuariosActualizarRoute
  '/usuarios/buscar': typeof UsuariosBuscarRoute
  '/usuarios/crear': typeof UsuariosCrearRoute
  '/usuarios/eliminar': typeof UsuariosEliminarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/horarios': typeof HorariosRoute
  '/inventario': typeof InventarioRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/registros': typeof RegistrosRoute
  '/reservas': typeof ReservasRouteWithChildren
  '/categorias/actualizar': typeof CategoriasActualizarRoute
  '/categorias/buscar': typeof CategoriasBuscarRoute
  '/categorias/crear': typeof CategoriasCrearRoute
  '/categorias/eliminar': typeof CategoriasEliminarRoute
  '/categorias/listar': typeof CategoriasListarRoute
  '/deportes/actualizar': typeof DeportesActualizarRoute
  '/deportes/buscar': typeof DeportesBuscarRoute
  '/deportes/crear': typeof DeportesCrearRoute
  '/deportes/eliminar': typeof DeportesEliminarRoute
  '/deportes/listar': typeof DeportesListarRoute
  '/perfil/datos-academicos': typeof PerfilDatosAcademicosRoute
  '/perfil/datos-familiares': typeof PerfilDatosFamiliaresRoute
  '/perfil/datos-personales': typeof PerfilDatosPersonalesRoute
  '/perfil/valoracion-medica': typeof PerfilValoracionMedicaRoute
  '/reservas/articulos': typeof ReservasArticulosRoute
  '/reservas/lugares': typeof ReservasLugaresRoute
  '/usuarios/actualizar': typeof UsuariosActualizarRoute
  '/usuarios/buscar': typeof UsuariosBuscarRoute
  '/usuarios/crear': typeof UsuariosCrearRoute
  '/usuarios/eliminar': typeof UsuariosEliminarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/horarios'
    | '/inventario'
    | '/login'
    | '/registro'
    | '/registros'
    | '/reservas'
    | '/categorias/actualizar'
    | '/categorias/buscar'
    | '/categorias/crear'
    | '/categorias/eliminar'
    | '/categorias/listar'
    | '/deportes/actualizar'
    | '/deportes/buscar'
    | '/deportes/crear'
    | '/deportes/eliminar'
    | '/deportes/listar'
    | '/perfil/datos-academicos'
    | '/perfil/datos-familiares'
    | '/perfil/datos-personales'
    | '/perfil/valoracion-medica'
    | '/reservas/articulos'
    | '/reservas/lugares'
    | '/usuarios/actualizar'
    | '/usuarios/buscar'
    | '/usuarios/crear'
    | '/usuarios/eliminar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/horarios'
    | '/inventario'
    | '/login'
    | '/registro'
    | '/registros'
    | '/reservas'
    | '/categorias/actualizar'
    | '/categorias/buscar'
    | '/categorias/crear'
    | '/categorias/eliminar'
    | '/categorias/listar'
    | '/deportes/actualizar'
    | '/deportes/buscar'
    | '/deportes/crear'
    | '/deportes/eliminar'
    | '/deportes/listar'
    | '/perfil/datos-academicos'
    | '/perfil/datos-familiares'
    | '/perfil/datos-personales'
    | '/perfil/valoracion-medica'
    | '/reservas/articulos'
    | '/reservas/lugares'
    | '/usuarios/actualizar'
    | '/usuarios/buscar'
    | '/usuarios/crear'
    | '/usuarios/eliminar'
  id:
    | '__root__'
    | '/'
    | '/horarios'
    | '/inventario'
    | '/login'
    | '/registro'
    | '/registros'
    | '/reservas'
    | '/categorias/actualizar'
    | '/categorias/buscar'
    | '/categorias/crear'
    | '/categorias/eliminar'
    | '/categorias/listar'
    | '/deportes/actualizar'
    | '/deportes/buscar'
    | '/deportes/crear'
    | '/deportes/eliminar'
    | '/deportes/listar'
    | '/perfil/datos-academicos'
    | '/perfil/datos-familiares'
    | '/perfil/datos-personales'
    | '/perfil/valoracion-medica'
    | '/reservas/articulos'
    | '/reservas/lugares'
    | '/usuarios/actualizar'
    | '/usuarios/buscar'
    | '/usuarios/crear'
    | '/usuarios/eliminar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HorariosRoute: typeof HorariosRoute
  InventarioRoute: typeof InventarioRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  RegistrosRoute: typeof RegistrosRoute
  ReservasRoute: typeof ReservasRouteWithChildren
  CategoriasActualizarRoute: typeof CategoriasActualizarRoute
  CategoriasBuscarRoute: typeof CategoriasBuscarRoute
  CategoriasCrearRoute: typeof CategoriasCrearRoute
  CategoriasEliminarRoute: typeof CategoriasEliminarRoute
  CategoriasListarRoute: typeof CategoriasListarRoute
  DeportesActualizarRoute: typeof DeportesActualizarRoute
  DeportesBuscarRoute: typeof DeportesBuscarRoute
  DeportesCrearRoute: typeof DeportesCrearRoute
  DeportesEliminarRoute: typeof DeportesEliminarRoute
  DeportesListarRoute: typeof DeportesListarRoute
  PerfilDatosAcademicosRoute: typeof PerfilDatosAcademicosRoute
  PerfilDatosFamiliaresRoute: typeof PerfilDatosFamiliaresRoute
  PerfilDatosPersonalesRoute: typeof PerfilDatosPersonalesRoute
  PerfilValoracionMedicaRoute: typeof PerfilValoracionMedicaRoute
  UsuariosActualizarRoute: typeof UsuariosActualizarRoute
  UsuariosBuscarRoute: typeof UsuariosBuscarRoute
  UsuariosCrearRoute: typeof UsuariosCrearRoute
  UsuariosEliminarRoute: typeof UsuariosEliminarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registros': {
      id: '/registros'
      path: '/registros'
      fullPath: '/registros'
      preLoaderRoute: typeof RegistrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/eliminar': {
      id: '/usuarios/eliminar'
      path: '/usuarios/eliminar'
      fullPath: '/usuarios/eliminar'
      preLoaderRoute: typeof UsuariosEliminarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/crear': {
      id: '/usuarios/crear'
      path: '/usuarios/crear'
      fullPath: '/usuarios/crear'
      preLoaderRoute: typeof UsuariosCrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/buscar': {
      id: '/usuarios/buscar'
      path: '/usuarios/buscar'
      fullPath: '/usuarios/buscar'
      preLoaderRoute: typeof UsuariosBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios/actualizar': {
      id: '/usuarios/actualizar'
      path: '/usuarios/actualizar'
      fullPath: '/usuarios/actualizar'
      preLoaderRoute: typeof UsuariosActualizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas/lugares': {
      id: '/reservas/lugares'
      path: '/lugares'
      fullPath: '/reservas/lugares'
      preLoaderRoute: typeof ReservasLugaresRouteImport
      parentRoute: typeof ReservasRoute
    }
    '/reservas/articulos': {
      id: '/reservas/articulos'
      path: '/articulos'
      fullPath: '/reservas/articulos'
      preLoaderRoute: typeof ReservasArticulosRouteImport
      parentRoute: typeof ReservasRoute
    }
    '/perfil/valoracion-medica': {
      id: '/perfil/valoracion-medica'
      path: '/perfil/valoracion-medica'
      fullPath: '/perfil/valoracion-medica'
      preLoaderRoute: typeof PerfilValoracionMedicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/datos-personales': {
      id: '/perfil/datos-personales'
      path: '/perfil/datos-personales'
      fullPath: '/perfil/datos-personales'
      preLoaderRoute: typeof PerfilDatosPersonalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/datos-familiares': {
      id: '/perfil/datos-familiares'
      path: '/perfil/datos-familiares'
      fullPath: '/perfil/datos-familiares'
      preLoaderRoute: typeof PerfilDatosFamiliaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/datos-academicos': {
      id: '/perfil/datos-academicos'
      path: '/perfil/datos-academicos'
      fullPath: '/perfil/datos-academicos'
      preLoaderRoute: typeof PerfilDatosAcademicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deportes/listar': {
      id: '/deportes/listar'
      path: '/deportes/listar'
      fullPath: '/deportes/listar'
      preLoaderRoute: typeof DeportesListarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deportes/eliminar': {
      id: '/deportes/eliminar'
      path: '/deportes/eliminar'
      fullPath: '/deportes/eliminar'
      preLoaderRoute: typeof DeportesEliminarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deportes/crear': {
      id: '/deportes/crear'
      path: '/deportes/crear'
      fullPath: '/deportes/crear'
      preLoaderRoute: typeof DeportesCrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deportes/buscar': {
      id: '/deportes/buscar'
      path: '/deportes/buscar'
      fullPath: '/deportes/buscar'
      preLoaderRoute: typeof DeportesBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deportes/actualizar': {
      id: '/deportes/actualizar'
      path: '/deportes/actualizar'
      fullPath: '/deportes/actualizar'
      preLoaderRoute: typeof DeportesActualizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/listar': {
      id: '/categorias/listar'
      path: '/categorias/listar'
      fullPath: '/categorias/listar'
      preLoaderRoute: typeof CategoriasListarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/eliminar': {
      id: '/categorias/eliminar'
      path: '/categorias/eliminar'
      fullPath: '/categorias/eliminar'
      preLoaderRoute: typeof CategoriasEliminarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/crear': {
      id: '/categorias/crear'
      path: '/categorias/crear'
      fullPath: '/categorias/crear'
      preLoaderRoute: typeof CategoriasCrearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/buscar': {
      id: '/categorias/buscar'
      path: '/categorias/buscar'
      fullPath: '/categorias/buscar'
      preLoaderRoute: typeof CategoriasBuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias/actualizar': {
      id: '/categorias/actualizar'
      path: '/categorias/actualizar'
      fullPath: '/categorias/actualizar'
      preLoaderRoute: typeof CategoriasActualizarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReservasRouteChildren {
  ReservasArticulosRoute: typeof ReservasArticulosRoute
  ReservasLugaresRoute: typeof ReservasLugaresRoute
}

const ReservasRouteChildren: ReservasRouteChildren = {
  ReservasArticulosRoute: ReservasArticulosRoute,
  ReservasLugaresRoute: ReservasLugaresRoute,
}

const ReservasRouteWithChildren = ReservasRoute._addFileChildren(
  ReservasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HorariosRoute: HorariosRoute,
  InventarioRoute: InventarioRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  RegistrosRoute: RegistrosRoute,
  ReservasRoute: ReservasRouteWithChildren,
  CategoriasActualizarRoute: CategoriasActualizarRoute,
  CategoriasBuscarRoute: CategoriasBuscarRoute,
  CategoriasCrearRoute: CategoriasCrearRoute,
  CategoriasEliminarRoute: CategoriasEliminarRoute,
  CategoriasListarRoute: CategoriasListarRoute,
  DeportesActualizarRoute: DeportesActualizarRoute,
  DeportesBuscarRoute: DeportesBuscarRoute,
  DeportesCrearRoute: DeportesCrearRoute,
  DeportesEliminarRoute: DeportesEliminarRoute,
  DeportesListarRoute: DeportesListarRoute,
  PerfilDatosAcademicosRoute: PerfilDatosAcademicosRoute,
  PerfilDatosFamiliaresRoute: PerfilDatosFamiliaresRoute,
  PerfilDatosPersonalesRoute: PerfilDatosPersonalesRoute,
  PerfilValoracionMedicaRoute: PerfilValoracionMedicaRoute,
  UsuariosActualizarRoute: UsuariosActualizarRoute,
  UsuariosBuscarRoute: UsuariosBuscarRoute,
  UsuariosCrearRoute: UsuariosCrearRoute,
  UsuariosEliminarRoute: UsuariosEliminarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
